function createList(typeDev, arr) {
    var count = 0;
    var txtObj = typeDev + ':[';
    arr.forEach(function(element, i, a) {

        txtObj += '{oid:"' + element[0] + '",' +
            'name:"' + element[1] + '",' +
            'descr:"' + element[2] + '"}';
        count++;
        if (i !== a.length - 1) {
            txtObj += ','
        }
    });
    txtObj += ']'

    console.log('Создан массив, кол-во объектов: ', count + 1);
    return txtObj;
}

var routers = [
    ['1.3.6.1.2.1.1.7', 'sysServices', 'A value which indicates the set of services that this entity primarily offers'],
    ['1.3.6.1.2.1.4.1', 'ipForwarding', 'The indication of whether this entity is acting as an IPv4 router'],
    ['[1.3.6.1.2.1.15.3', 'bgpPeerTable', 'BGP peer table'],
    ['1.3.6.1.2.1.14.2', 'ospfAreaTable', 'Information describing the configured parameters and cumulative statistics'],
    ['1.3.6.1.2.1.14.4', 'ospfLsdbTabl', 'The OSPF Process\ s link state database(LSDB)'],
    ['1.3.6.1.3.96.1.3', 'mplsInSegmentTable', 'This table contains a collection of incoming segments to an LSR'],
    ['1.3.6.1.3.96.1.6', 'mplsOutSegmentTable', 'This table contains a representation of the outgoing segments from an LSR'],
    ['1.3.6.1.3.118.1.2.2', 'mplsVpnVrfTable', 'mplsVpnVrfTable']
];


var switches = [
    ['1.3.6.1.2.1.17.0', 'dot1dNotifications', 'Notifications'],
    ['1.3.6.1.2.1.17.1', 'dot1dBase', '"dot1dBase" group'],
    ['1.3.6.1.2.1.17.2', 'dot1dStp', '"dot1dStp" group'],
    ['1.3.6.1.2.1.17.3', 'dot1dSr', '"dot1dSr" group'],
    ['1.3.6.1.2.1.17.4', 'dot1dTp', '"dot1dTp" group'],
    ['1.3.6.1.2.1.17.5', 'dot1dStatic', '"dot1dStatic" group'],
    ['1.3.6.1.2.1.17.6', 'pBridgeMIB', 'The Bridge MIB Extension module'],
    ['1.3.6.1.2.1.17.7', 'qBridgeMIB', 'The VLAN Bridge MIB module'],
    ['1.3.6.1.2.1.17.8', 'dot1dConformance', 'Conformance'],
    ['1.3.6.1.2.1.17.10', 'dot1dPortPair', '"dot1dPortPair" group']
]
var hosts = [
    ['1.3.6.1.2.1.25.1', 'hrSystem', 'System'],
    ['1.3.6.1.2.1.25.2', 'hrStorage', 'Storage'],
    ['1.3.6.1.2.1.25.3', 'hrDevice', 'Host resources device'],
    ['1.3.6.1.2.1.25.4', 'hrSWRun', 'Host resources software run'],
    ['1.3.6.1.2.1.25.5', 'hrSWRunPerf', 'Host resources software run performance'],
    ['1.3.6.1.2.1.25.6', 'hrSWInstalled', 'Host resources software installed'],
    ['1.3.6.1.2.1.25.7', 'hrMIBAdminInfo', 'Admin info']
]

var ups = [
    ['1.3.6.1.2.1.33.1.1.1', 'upsIdentManufacturer', 'The name of the UPS manufacturer'],
    ['1.3.6.1.2.1.33.1.1.2', 'upsIdentModel', 'The UPS Model designation'],
    ['1.3.6.1.2.1.33.1.1.3', 'upsIdentUPSSoftwareVersion', 'The UPS firmware/software version(s)'],
    ['1.3.6.1.2.1.33.1.1.4', 'upsIdentAgentSoftwareVersion', 'The UPS agent software version'],
    ['1.3.6.1.2.1.33.1.1.5', 'upsIdentName', 'A string identifying the UPS'],
    ['1.3.6.1.2.1.33.1.1.6', 'upsIdentAttachedDevices', 'A string identifying the devices attached to the output(s) of the UPS'],
    ['1.3.6.1.2.1.33.1.2.1', 'upsBatteryStatus', 'The indication of the capacity remaining in the UPS systems batteries'],
    ['1.3.6.1.2.1.33.1.2.2', 'upsSecondsOnBattery', 'If the unit is on battery power, the elapsed time since the UPS last switched to battery power'],
    ['1.3.6.1.2.1.33.1.2.3', 'upsEstimatedMinutesRemaining', 'An estimate of the time to battery charge depletion'],
    ['1.3.6.1.2.1.33.1.2.4', 'upsEstimatedChargeRemaining', 'An estimate of the battery charge remaining expressed as a percent of full charge'],
    ['1.3.6.1.2.1.33.1.2.5', 'upsBatteryVoltage', 'The magnitude of the present battery voltage'],
    ['1.3.6.1.2.1.33.1.2.6', 'upsBatteryCurrent', 'The present battery current'],
    ['1.3.6.1.2.1.33.1.2.7', 'upsBatteryTemperature', 'The ambient temperature at or near the UPS Battery casing'],
    ['1.3.6.1.2.1.33.1.3.1', 'upsInputLineBads', 'A count of the number of times the input entered an out-of-tolerance condition as defined by the manufacturer'],
    ['1.3.6.1.2.1.33.1.3.2', 'upsInputNumLines', 'The number of input lines utilized in this device'],
    ['1.3.6.1.2.1.33.1.3.3.1.1', 'upsInputLineIndex', 'The input line identifier'],
    ['1.3.6.1.2.1.33.1.3.3.1.2', 'upsInputFrequency', 'The present input frequency'],
    ['1.3.6.1.2.1.33.1.3.3.1.3', 'upsInputVoltage', 'The magnitude of the present input voltage'],
    ['1.3.6.1.2.1.33.1.3.3.1.4', 'upsInputCurrent', 'The magnitude of the present input current'],
    ['1.3.6.1.2.1.33.1.3.3.1.5', 'upsInputTruePower', 'The magnitude of the present input true power'],
    ['1.3.6.1.2.1.33.1.4.1', 'upsOutputSource', 'The present source of output power'],
    ['1.3.6.1.2.1.33.1.4.2', 'upsOutputFrequency', 'The present output frequency'],
    ['1.3.6.1.2.1.33.1.4.3', 'upsOutputNumLines', 'The number of output lines utilized in this device'],
    ['1.3.6.1.2.1.33.1.4.4.1.1', 'upsOutputLineIndex', 'The output line identifier'],
    ['1.3.6.1.2.1.33.1.4.4.1.2', 'upsOutputVoltage', 'The present output voltage'],
    ['1.3.6.1.2.1.33.1.4.4.1.3', 'upsOutputCurrent', 'The present output current'],
    ['1.3.6.1.2.1.33.1.4.4.1.4', 'upsOutputPower', 'The present output true power'],
    ['1.3.6.1.2.1.33.1.4.4.1.5', 'upsOutputPercentLoad', 'The percentage of the UPS power capacity'],
    ['1.3.6.1.2.1.33.1.5.1', 'upsBypassFrequency', 'The present bypass frequency'],
    ['1.3.6.1.2.1.33.1.5.2', 'upsBypassNumLines', 'The number of bypass lines utilized in this device'],
    ['1.3.6.1.2.1.33.1.5.3.1.1', 'upsBypassLineIndex', 'The bypass line identifier'],
    ['1.3.6.1.2.1.33.1.5.3.1.2', 'upsBypassVoltage', 'The present bypass voltage'],
    ['1.3.6.1.2.1.33.1.5.3.1.3', 'upsBypassCurrent', 'The present bypass current'],
    ['1.3.6.1.2.1.33.1.5.3.1.4', 'upsBypassPower', 'The present true power conveyed by the bypass'],
    ['1.3.6.1.2.1.33.1.6.1', 'upsAlarmsPresent', 'The present number of active alarm conditions'],
    ['1.3.6.1.2.1.33.1.6.2.1.1', 'upsAlarmId', 'A unique identifier for an alarm condition'],
    ['1.3.6.1.2.1.33.1.6.2.1.2', 'upsAlarmDescr', 'A reference to an alarm description object'],
    ['1.3.6.1.2.1.33.1.6.2.1.3', 'upsAlarmTime', 'The value of sysUpTime when the alarm condition was detected'],
    ['1.3.6.1.2.1.33.1.6.3.1', 'upsAlarmBatteryBad', 'One or more batteries have been determined to require replacement'],
    ['1.3.6.1.2.1.33.1.6.3.2', 'upsAlarmOnBattery', 'The UPS is drawing power from the batteries'],
    ['1.3.6.1.2.1.33.1.6.3.3', 'upsAlarmLowBattery', 'The remaining battery run-time is less than or equal to upsConfigLowBattTime'],
    ['1.3.6.1.2.1.33.1.6.3.4', 'upsAlarmDepletedBattery', 'The UPS will be unable to sustain the present load when and if the utility power is lost'],
    ['1.3.6.1.2.1.33.1.6.3.5', 'upsAlarmTempBad', 'A temperature is out of tolerance'],
    ['1.3.6.1.2.1.33.1.6.3.6', 'upsAlarmInputBad', 'An input condition is out of tolerance'],
    ['1.3.6.1.2.1.33.1.6.3.7', 'upsAlarmOutputBad', 'An output condition (other than OutputOverload) is out of tolerance'],
    ['1.3.6.1.2.1.33.1.6.3.8', 'upsAlarmOutputOverload', 'The output load exceeds the UPS output capacity'],
    ['1.3.6.1.2.1.33.1.6.3.9', 'upsAlarmOnBypass', 'The Bypass is presently engaged on the UPS'],
    ['1.3.6.1.2.1.33.1.6.3.10', 'upsAlarmBypassBad', 'The Bypass is out of tolerance'],
    ['1.3.6.1.2.1.33.1.6.3.11', 'upsAlarmOutputOffAsRequested', 'The UPS has shutdown as requested, i.e., the output is off'],
    ['1.3.6.1.2.1.33.1.6.3.12', 'upsAlarmUpsOffAsRequested', 'The entire UPS has shutdown as commanded'],
    ['1.3.6.1.2.1.33.1.6.3.13', 'upsAlarmChargerFailed', 'An uncorrected problem has been detected within the UPS charger subsystem'],
    ['1.3.6.1.2.1.33.1.6.3.14', 'upsAlarmUpsOutputOff', 'The output of the UPS is in the off state'],
    ['1.3.6.1.2.1.33.1.6.3.15', 'upsAlarmUpsSystemOff', 'The UPS system is in the off state'],
    ['1.3.6.1.2.1.33.1.6.3.16', 'upsAlarmFanFailure', 'The failure of one or more fans in the UPS has been detected'],
    ['1.3.6.1.2.1.33.1.6.3.17', 'upsAlarmFuseFailure', 'The failure of one or more fuses has been detected'],
    ['1.3.6.1.2.1.33.1.6.3.18', 'upsAlarmGeneralFault', 'A general fault in the UPS has been detected'],
    ['1.3.6.1.2.1.33.1.6.3.19', 'upsAlarmDiagnosticTestFailed', 'The result of the last diagnostic test indicates a failure'],
    ['1.3.6.1.2.1.33.1.6.3.20', 'upsAlarmCommunicationsLost', 'A problem has been encountered in the communications between the agent and the UPS'],
    ['1.3.6.1.2.1.33.1.6.3.21', 'upsAlarmAwaitingPower', 'The UPS output is off and the UPS is awaiting the return of input power'],
    ['1.3.6.1.2.1.33.1.6.3.22', 'upsAlarmShutdownPending', 'A upsShutdownAfterDelay countdown is underway'],
    ['1.3.6.1.2.1.33.1.6.3.23', 'upsAlarmShutdownImminent', 'The UPS will turn off power to the load in less than 5 seconds'],
    ['1.3.6.1.2.1.33.1.6.3.24', 'upsAlarmTestInProgress', 'A test is in progress, as initiated and indicated by the Test Group'],
    ['1.3.6.1.2.1.33.1.6.4.0', 'upsAlarmID', 'upsAlarmID '],
    ['1.3.6.1.2.1.33.1.6.5.0', 'upsAlarmDESCR', 'upsAlarmDESCR'],
    ['1.3.6.1.2.1.33.1.7.1', 'upsTestId', 'The test is named by an OBJECT IDENTIFIER which allows a standard mechanism for the initiation of tests'],
    ['1.3.6.1.2.1.33.1.7.2', 'upsTestSpinLock', 'A spin lock on the test subsystem'],
    ['1.3.6.1.2.1.33.1.7.3', 'upsTestResultsSummary', 'The results of the current or last UPS diagnostics test performed'],
    ['1.3.6.1.2.1.33.1.7.4', 'upsTestResultsDetail', 'Additional information about upsTestResultsSummary'],
    ['1.3.6.1.2.1.33.1.7.5', 'upsTestStartTime', 'The value of sysUpTime at the time the test in progress was initiated'],
    ['1.3.6.1.2.1.33.1.7.6', 'upsTestElapsedTime', 'The amount of time, in TimeTicks, since the test in progress was initiated'],
    ['1.3.6.1.2.1.33.1.7.7.1', 'upsTestNoTestsInitiated', 'No tests have been initiated and no test is in progress'],
    ['1.3.6.1.2.1.33.1.7.7.2', 'upsTestAbortTestInProgress', 'The test in progress is to be aborted'],
    ['1.3.6.1.2.1.33.1.7.7.3', 'upsTestGeneralSystemsTest', 'The manufacturers standard test of UPS device systems'],
    ['1.3.6.1.2.1.33.1.7.7.4', 'upsTestQuickBatteryTest', 'A test that is sufficient to determine if the battery needs replacement'],
    ['1.3.6.1.2.1.33.1.7.7.5', 'upsTestDeepBatteryCalibration', 'The system is placed on battery to a discharge level, set by the manufacturer'],
    ['1.3.6.1.2.1.33.1.8.1', 'upsShutdownType', 'This object determines the nature of the action to be taken at the time when the countdown of the upsShutdownAfterDelay and upsRebootWithDuration objects reaches zero'],
    ['1.3.6.1.2.1.33.1.8.2', 'upsShutdownAfterDelay', 'Setting this object will shutdown either the UPS output or the UPS system after the indicated number of seconds'],
    ['1.3.6.1.2.1.33.1.8.3', 'upsStartupAfterDelay', 'Setting this object will start the output after the indicated number of seconds, including starting the UPS'],
    ['1.3.6.1.2.1.33.1.8.4', 'upsRebootWithDuration', 'Setting this object will immediately shutdown'],
    ['1.3.6.1.2.1.33.1.8.5', 'upsAutoRestart', 'Setting this object to on will cause the UPS system to restart after a shutdown'],
    ['1.3.6.1.2.1.33.1.9.1', 'upsConfigInputVoltage', 'The magnitude of the nominal input voltage'],
    ['1.3.6.1.2.1.33.1.9.2', 'upsConfigInputFreq', 'The nominal input frequency'],
    ['1.3.6.1.2.1.33.1.9.3', 'upsConfigOutputVoltage', 'The magnitude of the nominal output voltage'],
    ['1.3.6.1.2.1.33.1.9.4', 'upsConfigOutputFreq', 'The nominal output frequency'],
    ['1.3.6.1.2.1.33.1.9.5', 'upsConfigOutputVA', 'The magnitude of the nominal Volt-Amp rating'],
    ['1.3.6.1.2.1.33.1.9.6', 'upsConfigOutputPower', 'The magnitude of the nominal true power rating'],
    ['1.3.6.1.2.1.33.1.9.7', 'upsConfigLowBattTime', 'The value of upsEstimatedMinutesRemaining at which a lowBattery condition is declared'],
    ['1.3.6.1.2.1.33.1.9.8', 'upsConfigAudibleStatus', 'The requested state of the audible alarm'],
    ['1.3.6.1.2.1.33.1.9.9', 'upsConfigLowVoltageTransferPoint', 'he minimum input line voltage allowed before the UPS system transfers to battery backup'],
    ['1.3.6.1.2.1.33.1.9.10', 'upsConfigHighVoltageTransferPoint', 'The maximum line voltage allowed before the UPS system transfers to battery backup'],
    ['1.3.6.1.2.1.33.2.1', 'upsTrapOnBattery', 'The UPS is operating on battery power'],
    ['1.3.6.1.2.1.33.2.2', 'upsTrapTestCompleted', 'This trap is sent upon completion of a UPS diagnostic test'],
    ['1.3.6.1.2.1.33.2.3', 'upsTrapAlarmEntryAdded', 'This trap is sent each time an alarm is inserted into to the alarm table'],
    ['1.3.6.1.2.1.33.2.4', 'upsTrapAlarmEntryRemoved', 'This trap is sent each time an alarm is removed from the alarm table'],
    ['1.3.6.1.2.1.33.3.1.1', 'upsSubsetCompliance', 'The compliance statement for UPSs that only support the two-contact communication protocol'],
    ['1.3.6.1.2.1.33.3.1.2', 'upsBasicCompliance', 'The compliance statement for UPSs that support full-featured functions, such as control'],
    ['1.3.6.1.2.1.33.3.1.3', 'upsFullCompliance', 'The compliance statement for UPSs that support advanced full-featured functions'],
    ['1.3.6.1.2.1.33.3.2.1', 'upsSubsetGroups', 'Subset groups'],
    ['1.3.6.1.2.1.33.3.2.1.1', 'upsSubsetIdentGroup', 'The upsSubsetIdentGroup defines objects which are common across all UPSs which meet subset compliance'],
    ['1.3.6.1.2.1.33.3.2.1.2', 'upsSubsetBatteryGroup', 'The upsSubsetBatteryGroup defines the objects that are common to battery groups of two-contact UPSs'],
    ['1.3.6.1.2.1.33.3.2.1.3', 'upsSubsetInputGroup', 'The upsSubsetInputGroup defines the objects that are common to the Input groups of two-contact UPSs'],
    ['1.3.6.1.2.1.33.3.2.1.4', 'upsSubsetOutputGroup', 'The upsSubsetOutputGroup defines the objects that are common to the Output groups of two-contact UPSs'],
    ['1.3.6.1.2.1.33.3.2.1.6', 'upsSubsetAlarmGroup', 'The upsSubsetAlarmGroup defines the objects that are common to the Alarm groups of two-contact UPSs'],
    ['1.3.6.1.2.1.33.3.2.1.8', 'upsSubsetControlGroup', 'The upsSubsetControlGroup defines the objects that are common to the Control groups of two-contact UPSs'],
    ['1.3.6.1.2.1.33.3.2.1.9', 'upsSubsetConfigGroup', 'The upsSubsetConfigGroup defines the objects that are common to the Config groups of two-contact UPSs'],
    ['1.3.6.1.2.1.33.3.2.2.1', 'upsBasicIdentGroup', 'The upsBasicIdentGroup defines objects which are common to the Ident group of compliant UPSs which support basic functions'],
    ['1.3.6.1.2.1.33.3.2.2.2', 'upsBasicBatteryGroup', 'The upsBasicBatteryGroup defines the objects that are common to the battery groups of compliant UPSs which support basic functions'],
    ['1.3.6.1.2.1.33.3.2.2.3', 'upsBasicInputGroup', 'The upsBasicInputGroup defines the objects that are common to the Input groups of compliant UPSs which support basic functions'],
    ['1.3.6.1.2.1.33.3.2.2.4', 'upsBasicOutputGroup', 'The upsBasicOutputGroup defines the objects that are common to the Output groups of compliant UPSs which support basic functions'],
    ['1.3.6.1.2.1.33.3.2.2.5', 'upsBasicBypassGroup', 'The upsBasicBypassGroup defines the objects that are common to the Bypass groups of compliant UPSs which support basic functions'],
    ['1.3.6.1.2.1.33.3.2.2.6', 'upsBasicAlarmGroup', 'The upsBasicAlarmGroup defines the objects that are common to the Alarm groups of compliant UPSs which support basic functions'],
    ['1.3.6.1.2.1.33.3.2.2.7', 'upsBasicTestGroup', 'The upsBasicTestGroup defines the objects that are common to the Test groups of compliant UPSs which support basic functions'],
    ['1.3.6.1.2.1.33.3.2.2.8', 'upsBasicControlGroup', 'The upsBasicControlGroup defines the objects that are common to the Control groups of compliant UPSs which support basic functions'],
    ['1.3.6.1.2.1.33.3.2.2.9', 'upsBasicConfigGroup', 'The upsBasicConfigGroup defines the objects that are common to the Config groups of UPSs which support basic functions'],
    ['1.3.6.1.2.1.33.3.2.3.1', 'upsFullIdentGroup', 'The upsFullIdentGroup defines objects which are common to the Ident group of fully compliant UPSs'],
    ['1.3.6.1.2.1.33.3.2.3.2', 'upsFullBatteryGroup', 'The upsFullBatteryGroup defines the objects that are common to the battery groups of fully compliant UPSs'],
    ['1.3.6.1.2.1.33.3.2.3.3', 'upsFullInputGroup', 'The upsFullInputGroup defines the objects that are common to the Input groups of fully compliant UPSs'],
    ['1.3.6.1.2.1.33.3.2.3.4', 'upsFullOutputGroup', 'The upsFullOutputGroup defines the objects that are common to the Output groups of fully compliant UPSs'],
    ['1.3.6.1.2.1.33.3.2.3.5', 'upsFullBypassGroup', 'The upsFullBypassGroup defines the objects that are common to the Bypass groups of fully compliant UPSs'],
    ['1.3.6.1.2.1.33.3.2.3.6', 'upsFullAlarmGroup', 'The upsFullAlarmGroup defines the objects that are common to the Alarm groups of fully compliant UPSs'],
    ['1.3.6.1.2.1.33.3.2.3.7', 'upsFullTestGroup', 'The upsFullTestGroup defines the objects that are common to the Test groups of fully compliant UPSs'],
    ['1.3.6.1.2.1.33.3.2.3.8', 'upsFullControlGroup', 'The upsFullControlGroup defines the objects that are common to the Control groups of fully compliant UPSs'],
    ['1.3.6.1.2.1.33.3.2.3.9', 'upsFullConfigGroup', 'The upsFullConfigGroup defines the objects that are common to the Config groups of fully compliant UPSs']
]

var printers = [
    ['1.3.6.1.2.1.43.2.2.1', 'prtGeneralGroup', 'The general printer group'],
    ['1.3.6.1.2.1.43.2.2.2', 'prtResponsiblePartyGroup', 'The responsible party group contains contact information for humans responsible for the printer '],
    ['1.3.6.1.2.1.43.2.2.3', 'prtInputGroup', 'The input group'],
    ['1.3.6.1.2.1.43.2.2.4', 'prtExtendedInputGroup', 'The extended input group'],
    ['1.3.6.1.2.1.43.2.2.5', 'prtInputMediaGroup', 'The input media group'],
    ['1.3.6.1.2.1.43.2.2.6', 'prtOutputGroup', 'The output group'],
    ['1.3.6.1.2.1.43.2.2.7', 'prtExtendedOutputGroup', 'The extended output group'],
    ['1.3.6.1.2.1.43.2.2.8', 'prtOutputDimensionsGroup', 'The output dimensions group'],
    ['1.3.6.1.2.1.43.2.2.9', 'prtOutputFeaturesGroup', 'The output features group'],
    ['1.3.6.1.2.1.43.2.2.10', 'prtMarkerGroup', 'The marker group'],
    ['1.3.6.1.2.1.43.2.2.11', 'prtMarkerSuppliesGroup', 'The marker supplies group'],
    ['1.3.6.1.2.1.43.2.2.12', 'prtMarkerColorantGroup', 'The marker colorant group'],
    ['1.3.6.1.2.1.43.2.2.13', 'prtMediaPathGroup', 'The media path group'],
    ['1.3.6.1.2.1.43.2.2.14', 'prtChannelGroup', 'The channel group'],
    ['1.3.6.1.2.1.43.2.2.15', 'prtInterpreterGroup', 'The interpreter group'],
    ['1.3.6.1.2.1.43.2.2.16', 'prtConsoleGroup', 'The console group'],
    ['1.3.6.1.2.1.43.2.2.17', 'prtAlertTableGroup', 'The alert table group'],
    ['1.3.6.1.2.1.43.2.2.18', 'prtAlertTimeGroup', 'The alert time group'],
    ['1.3.6.1.2.1.43.2.2.19', 'prtAuxiliarySheetGroup', 'The auxiliary sheet group'],
    ['1.3.6.1.2.1.43.2.2.20', 'prtInputSwitchingGroup', 'The input switching group'],
    ['1.3.6.1.2.1.43.2.2.21', 'prtGeneralV2Group', 'The general printer group with new v2 objects'],
    ['1.3.6.1.2.1.43.2.2.22', 'prtAlertTableV2Group', 'The alert table group with new v2 objects and prtAlertIndex changed to MAX-ACCESS'],
    ['1.3.6.1.2.1.43.2.2.23', 'prtChannelV2Group', 'The channel group with a new v2 object'],
    ['1.3.6.1.2.1.43.2.2.24', 'prtAlertTrapGroup', 'prtAlertTrapGroup'],
    ['1.3.6.1.2.1.43.2.3', 'prtMIB2Compliance', 'The compliance statement for agents that implement the printer MIB V2'],
    ['1.3.6.1.2.1.43.2.4', 'prtMIB2Groups', 'prtMIB2Groups '],
    ['1.3.6.1.2.1.43.2.5', 'finMIBCompliance', 'The compliance statement for agents that implement the finisher MIB'],
    ['1.3.6.1.2.1.43.2.6.1', 'finDeviceGroup', 'The finisher device group'],
    ['1.3.6.1.2.1.43.2.6.2', 'finSupplyGroup', 'The finisher supply group'],
    ['1.3.6.1.2.1.43.2.6.3', 'finSupplyMediaInputGroup', 'The finisher supply, media input group'],
    ['1.3.6.1.2.1.43.2.6.4', 'finDeviceAttributeGroup', 'The finisher device attribute group'],
    ['1.3.6.1.2.1.43.5.1.1.1', 'prtGeneralConfigChanges', 'Counts configuration changes that change the capabilities of a printer'],
    ['1.3.6.1.2.1.43.5.1.1.2', 'prtGeneralCurrentLocalization', 'The value of the prtLocalizationIndex corresponding to the current language, country, and character set'],
    ['1.3.6.1.2.1.43.5.1.1.3', 'prtGeneralReset', 'Setting this value to `powerCycleReset, `resetToNVRAM, or `resetToFactoryDefaults will result in the resetting of the printer'],
    ['1.3.6.1.2.1.43.5.1.1.4', 'prtGeneralCurrentOperator', 'The name of the current human operator responsible for operating this printer'],
    ['1.3.6.1.2.1.43.5.1.1.5', 'prtGeneralServicePerson', 'The name of the last human responsible for servicing this printer'],
    ['1.3.6.1.2.1.43.5.1.1.6', 'prtInputDefaultIndex', 'The value of prtInputIndex corresponding to the default input sub-unit'],
    ['1.3.6.1.2.1.43.5.1.1.7', 'prtOutputDefaultIndex', 'The value of prtOutputIndex corresponding to the default output sub-unit'],
    ['1.3.6.1.2.1.43.5.1.1.8', 'prtMarkerDefaultIndex', 'The value of prtMarkerIndex corresponding to the default markersub-unit'],
    ['1.3.6.1.2.1.43.5.1.1.9', 'prtMediaPathDefaultIndex', 'The value of prtMediaPathIndex corresponding to the default media path'],
    ['1.3.6.1.2.1.43.5.1.1.10', 'prtConsoleLocalization', 'The value of the prtLocalizationIndex corresponding to the language, country, and character set to be used for the console'],
    ['1.3.6.1.2.1.43.5.1.1.11', 'prtConsoleNumberOfDisplayLines', 'The number of lines on the printers physical display'],
    ['1.3.6.1.2.1.43.5.1.1.12', 'prtConsoleNumberOfDisplayChars', 'The number of characters per line displayed on the physical display'],
    ['1.3.6.1.2.1.43.5.1.1.13', 'prtConsoleDisable', 'This object enables or disables manual input from the operators console'],
    ['1.3.6.1.2.1.43.5.1.1.14', 'prtAuxiliarySheetStartupPage', 'Used to enable or disable printing a startup page'],
    ['1.3.6.1.2.1.43.5.1.1.15', 'prtAuxiliarySheetBannerPage', 'Used to enable or disable printing banner pages at the beginning of jobs'],
    ['1.3.6.1.2.1.43.5.1.1.16', 'prtGeneralPrinterName', 'An administrator-specified name for this printer'],
    ['1.3.6.1.2.1.43.5.1.1.17', 'prtGeneralSerialNumber', 'A recorded serial number for this device that indexes some type device catalog or inventory'],
    ['1.3.6.1.2.1.43.5.1.1.18', 'prtAlertCriticalEvents', 'A running counter of the number of critical alert events that have been recorded in the alert table'],
    ['1.3.6.1.2.1.43.5.1.1.19', 'prtAlertAllEvents', 'A running counter of the total number of alert event entries that have been recorded in the alert table'],
    ['1.3.6.1.2.1.43.5.2.1.1', 'prtStorageRefSeqNumber', 'This value will be unique amongst all entries with a common value of hrStorageIndex'],
    ['1.3.6.1.2.1.43.5.2.1.2', 'prtStorageRefIndex', 'The value of the hrDeviceIndex of the printer device that this storageEntry is associated with'],
    ['1.3.6.1.2.1.43.5.3.1.1', 'prtDeviceRefSeqNumber', 'This value will be unique amongst all entries with a common value of hrDeviceIndex'],
    ['1.3.6.1.2.1.43.5.3.1.2', 'prtDeviceRefIndex', 'The value of the hrDeviceIndex of the printer device that this deviceEntry is associated with'],
    ['1.3.6.1.2.1.43.6.1.1.1', 'prtCoverIndex', 'A unique value used by the printer to identify this Cover sub-unit'],
    ['1.3.6.1.2.1.43.6.1.1.2', 'prtCoverDescription', 'The manufacturer provided cover sub-mechanism name in the localization specified by prtGeneralCurrentLocalization'],
    ['1.3.6.1.2.1.43.6.1.1.3', 'prtCoverStatus', 'The status of this cover sub-unit'],
    ['1.3.6.1.2.1.43.7.1.1.1', 'prtLocalizationIndex', 'A unique value used by the printer to identify this localization entry'],
    ['1.3.6.1.2.1.43.7.1.1.2', 'prtLocalizationLanguage', 'A two character language code from ISO 639'],
    ['1.3.6.1.2.1.43.7.1.1.3', 'prtLocalizationCountry', 'A two character country code from ISO 3166'],
    ['1.3.6.1.2.1.43.7.1.1.4', 'prtLocalizationCharacterSet', 'The coded character set used for this localization'],
    ['1.3.6.1.2.1.43.8.2.1.1', 'prtInputIndex', 'A unique value used by the printer to identify this input sub-unit'],
    ['1.3.6.1.2.1.43.8.2.1.2', 'prtInputType', 'The type of technology (discriminated primarily according to feeder mechanism type) employed by the input sub-unit'],
    ['1.3.6.1.2.1.43.8.2.1.3', 'prtInputDimUnit', 'The unit of measurement for use calculating and relaying dimensional values for this input sub-unit'],
    ['1.3.6.1.2.1.43.8.2.1.4', 'prtInputMediaDimFeedDirDeclared', 'This object provides the value of the declared dimension, in the feed direction, of the media that is (or, if empty, was or will be) in this input sub-unit'],
    ['1.3.6.1.2.1.43.8.2.1.5', 'prtInputMediaDimXFeedDirDeclared', 'This object provides the value of the declared dimension, in the cross feed direction, of the media that is (or, if empty, was or will be) in this input sub-unit'],
    ['1.3.6.1.2.1.43.8.2.1.6', 'prtInputMediaDimFeedDirChosen', 'The printer will act as if media of the chosen dimension (in the feed direction) is present in this input source'],
    ['1.3.6.1.2.1.43.8.2.1.7', 'prtInputMediaDimXFeedDirChosen', 'The printer will act as if media of the chosen dimension (in the cross feed direction) is present in this input source'],
    ['1.3.6.1.2.1.43.8.2.1.8', 'prtInputCapacityUnit', 'The unit of measurement for use in calculating and relaying capacity values for this input sub-unit'],
    ['1.3.6.1.2.1.43.8.2.1.9', 'prtInputMaxCapacity', 'The maximum capacity of the input sub-unit in input sub-unit capacity units (CapacityUnit)'],
    ['1.3.6.1.2.1.43.8.2.1.10', 'prtInputCurrentLevel', 'The current capacity of the input sub-unit in input sub-unit capacity units (CapacityUnit)'],
    ['1.3.6.1.2.1.43.8.2.1.11', 'prtInputStatus', 'The current status of this input sub-unit'],
    ['1.3.6.1.2.1.43.8.2.1.12', 'prtInputMediaName', 'A description of the media contained in this input sub-unit'],
    ['1.3.6.1.2.1.43.8.2.1.13', 'prtInputName', 'The name assigned to this input sub-unit'],
    ['1.3.6.1.2.1.43.8.2.1.14', 'prtInputVendorName', 'The vendor name of this input sub-unit'],
    ['1.3.6.1.2.1.43.8.2.1.15', 'prtInputModel', 'The model name of this input sub-unit'],
    ['1.3.6.1.2.1.43.8.2.1.16', 'prtInputVersion', 'The version of this input sub-unit'],
    ['1.3.6.1.2.1.43.8.2.1.17', 'prtInputSerialNumber', 'The serial number assigned to this input sub-unit'],
    ['1.3.6.1.2.1.43.8.2.1.18', 'prtInputDescription', 'A free-form text description of this input sub-unit in the localization specified by prtGeneralCurrentLocalization'],
    ['1.3.6.1.2.1.43.8.2.1.19', 'prtInputSecurity', 'Indicates if this input sub-unit has some security associated with it'],
    ['1.3.6.1.2.1.43.8.2.1.20', 'prtInputMediaWeight', 'The weight of the medium associated with this input sub-unit in grams / per meter squared. The value (-2) means unknown'],
    ['1.3.6.1.2.1.43.8.2.1.21', 'prtInputMediaType', 'The name of the type of medium associated with this input sub-unit'],
    ['1.3.6.1.2.1.43.8.2.1.22', 'prtInputMediaColor', 'The name of the color of the medium associated with this input sub-unit'],
    ['1.3.6.1.2.1.43.8.2.1.23', 'prtInputMediaFormParts', 'The number of parts associated with the medium associated with this input sub-unit if the medium is a multi-part form'],
    ['1.3.6.1.2.1.43.8.2.1.24', 'prtInputMediaLoadTimeout', 'When the printer is not able to print due to a subunit being empty or the requested media must be manually loaded, the printer will wait for the duration (in seconds) specified by this object'],
    ['1.3.6.1.2.1.43.8.2.1.25', 'prtInputNextIndex', 'The value of prtInputIndex corresponding to the input subunit which will be used when this input subunit is emptied and the time-out specified by prtInputMediaLoadTimeout expires'],
    ['1.3.6.1.2.1.43.8.2.1.26', 'prtinputnextindex', 'The value of prtInputIndex corresponding to the input subunit which will be used when this input subunit is emptied and the timeout specified by prtInputMediaLoadTimeout expires'],
    ['1.3.6.1.2.1.43.9.2.1.1', 'prtOutputIndex', 'A unique value used by this printer to identify this output sub-unit'],
    ['1.3.6.1.2.1.43.9.2.1.2', 'prtOutputType', 'The type of technology supported by this output sub-unit'],
    ['1.3.6.1.2.1.43.9.2.1.3', 'prtOutputCapacityUnit', 'The unit of measurement for use in calculating and relaying capacity values for this output sub-unit'],
    ['1.3.6.1.2.1.43.9.2.1.4', 'prtOutputMaxCapacity', 'The maximum capacity of this output sub-unit in output sub-unit capacity units (CapacityUnit)'],
    ['1.3.6.1.2.1.43.9.2.1.5', 'prtOutputRemainingCapacity', 'The remaining capacity of the possible output sub-unit capacity in output sub-unit capacity units (CapacityUnit) of this output sub-unit'],
    ['1.3.6.1.2.1.43.9.2.1.6', 'prtOutputStatus', 'The current status of this output sub-unit'],
    ['1.3.6.1.2.1.43.9.2.1.7', 'prtOutputName', 'The name assigned to this output sub-unit'],
    ['1.3.6.1.2.1.43.9.2.1.8', 'prtOutputVendorName', 'The vendor name of this output sub-unit'],
    ['1.3.6.1.2.1.43.9.2.1.9', 'prtOutputModel', 'The name assigned to this output sub-unit'],
    ['1.3.6.1.2.1.43.9.2.1.10', 'prtOutputVersion', 'The version of this output sub-unit'],
    ['1.3.6.1.2.1.43.9.2.1.11', 'prtOutputSerialNumber', 'The serial number assigned to this output sub-unit'],
    ['1.3.6.1.2.1.43.9.2.1.12', 'prtOutputDescription', ' A free-form text description of this output sub-unit in the localization specified by prtGeneralCurrentLocalization'],
    ['1.3.6.1.2.1.43.9.2.1.13', 'prtOutputSecurity', 'Indicates if this output sub-unit has some security associated with it and if that security is enabled or not'],
    ['1.3.6.1.2.1.43.9.2.1.14', 'prtOutputDimUnit', 'The unit of measurement for use in calculating and relaying dimensional values for this output sub-unit'],
    ['1.3.6.1.2.1.43.9.2.1.15', 'prtOutputMaxDimFeedDir', 'The maximum dimensions supported by this output sub-unit for measurements taken parallel relative to the feed direction associated with that sub-unit in output sub-unit dimensional units'],
    ['1.3.6.1.2.1.43.9.2.1.16', 'prtOutputMaxDimXFeedDir', 'The maximum dimensions supported by this output sub-unit for measurements taken ninety degrees relative to the feed direction associated with that sub-unit in output sub-unit dimensional units'],
    ['1.3.6.1.2.1.43.9.2.1.17', 'prtOutputMinDimFeedDir', 'The minimum dimensions supported by this output sub-unit for measurements taken parallel relative to the feed direction associated with that sub-unit in output sub-unit dimensional units'],
    ['1.3.6.1.2.1.43.9.2.1.18', 'prtOutputMinDimXFeedDir', 'The minimum dimensions supported by this output sub-unit for measurements taken ninety degrees relative to the feed direction associated with that sub-unit in output sub-unit dimensional units'],
    ['1.3.6.1.2.1.43.9.2.1.19', 'prtOutputStackingOrder', 'The current state of the stacking order for the associated output sub-unit'],
    ['1.3.6.1.2.1.43.9.2.1.20', 'prtOutputPageDeliveryOrientation', 'The reading surface that will be `up when pages are delivered to the associated output sub-unit'],
    ['1.3.6.1.2.1.43.9.2.1.21', 'prtOutputBursting', 'This object indicates that the outputing sub-unit supports bursting, and if so, whether the feature is enabled'],
    ['1.3.6.1.2.1.43.9.2.1.22', 'prtOutputDecollating', 'This object indicates that the output supports supports decollating, and if so, whether the feature is enabled'],
    ['1.3.6.1.2.1.43.9.2.1.23', 'prtOutputPageCollated', 'This object indicates that the output sub-unit supports page collation, and if so, whether the feature is enabled'],
    ['1.3.6.1.2.1.43.9.2.1.24', 'prtOutputOffsetStacking', 'This object indicates that the output supports supports offset stacking, and if so, whether the feature is enabled'],
    ['1.3.6.1.2.1.43.10.2.1.1', 'prtMarkerIndex', 'A unique value used by the printer to identify this marking SubUnitStatus'],
    ['1.3.6.1.2.1.43.10.2.1.2', 'prtMarkerMarkTech', 'The type of marking technology used for this marking sub-unit'],
    ['1.3.6.1.2.1.43.10.2.1.3', 'prtMarkerCounterUnit', 'The unit that will be used by the printer when reporting counter values for this marking sub-unit'],
    ['1.3.6.1.2.1.43.10.2.1.4', 'prtMarkerLifeCount', 'The count of the number of units of measure counted during the life of printer using units of measure as specified by CounterUnit'],
    ['1.3.6.1.2.1.43.10.2.1.5', 'prtMarkerPowerOnCount', 'The count of the number of units of measure counted since the equipment was most recently powered on using units of measure as specified by CounterUnit'],
    ['1.3.6.1.2.1.43.10.2.1.6', 'prtMarkerProcessColorants', 'The number of process colors supported by this marker'],
    ['1.3.6.1.2.1.43.10.2.1.7', 'prtMarkerSpotColorants', 'The number of spot colors supported by this marker'],
    ['1.3.6.1.2.1.43.10.2.1.8', 'prtMarkerAddressabilityUnit', 'The unit of measure of distances'],
    ['1.3.6.1.2.1.43.10.2.1.9', 'prtMarkerAddressabilityFeedDir', 'The number of addressable marking positions in the feed direction per 10000 units of measure specified by AddressabilityUnit'],
    ['1.3.6.1.2.1.43.10.2.1.10', 'prtMarkerAddressabilityXFeedDir', 'The number of addressable marking positions in the cross feed direction in 10000 units of measure specified by AddressabilityUnit'],
    ['1.3.6.1.2.1.43.10.2.1.11', 'prtMarkerNorthMargin', 'The margin, in units identified by AddressabilityUnit, from the leading edge of the medium as the medium flows throught the marking engine with the side to be imaged facing the observer'],
    ['1.3.6.1.2.1.43.10.2.1.12', 'prtMarkerSouthMargin', 'The margin from the South edge (see NorthMargin) of the medium in units identified by AddressabilityUnit'],
    ['1.3.6.1.2.1.43.10.2.1.13', 'prtMarkerWestMargin', 'The margin from the West edge (see NorthMargin) of the medium in units identified by AddressabilityUnit'],
    ['1.3.6.1.2.1.43.10.2.1.14', 'prtMarkerEastMargin', 'The margin from the East edge (see NorthMargin) of the medium in units identified by AddressabilityUnit'],
    ['1.3.6.1.2.1.43.10.2.1.15', 'prtMarkerStatus', 'The current status of this marker sub-unit'],
    ['1.3.6.1.2.1.43.11.1.1.1', 'prtMarkerSuppliesIndex', 'A unique value used by the printer to identify this marker supply'],
    ['1.3.6.1.2.1.43.11.1.1.2', 'prtMarkerSuppliesMarkerIndex', 'The value of prtMarkerIndex corresponding to the marking sub-unit with which this marker supply sub-unit is associated'],
    ['1.3.6.1.2.1.43.11.1.1.3', 'prtMarkerSuppliesColorantIndex', 'The value of prtMarkerColorantIndex corresponding to the colorant with which this marker supply sub-unit is associated'],
    ['1.3.6.1.2.1.43.11.1.1.4', 'prtMarkerSuppliesClass', 'Indicates whether this supply entity represents a supply container that is consumed or a receptacle that is filled'],
    ['1.3.6.1.2.1.43.11.1.1.5', 'prtMarkerSuppliesType', 'The type of this supply'],
    ['1.3.6.1.2.1.43.11.1.1.6', 'prtMarkerSuppliesDescription', 'The description of this supply container/receptacle in the localization specified by prtGeneralCurrentLocalization'],
    ['1.3.6.1.2.1.43.11.1.1.7', 'prtMarkerSuppliesSupplyUnit', 'Unit of this marker supply container/receptacle'],
    ['1.3.6.1.2.1.43.11.1.1.8', 'prtMarkerSuppliesMaxCapacity', 'The maximum capacity of this supply container/receptacle expressed in SupplyUnit'],
    ['1.3.6.1.2.1.43.11.1.1.9', 'prtMarkerSuppliesLevel', 'The current level if this supply is a container; the remaining space if this supply is a receptacle'],
    ['1.3.6.1.2.1.43.12.1.1.1', 'prtMarkerColorantIndex', 'A unique value used by the printer to identify this colorant'],
    ['1.3.6.1.2.1.43.12.1.1.2', 'prtMarkerColorantMarkerIndex', 'The value of prtMarkerIndex corresponding to the marker sub-unit with which this colorant entry is associated'],
    ['1.3.6.1.2.1.43.12.1.1.3', 'prtMarkerColorantRole', 'The role played by this colorant'],
    ['1.3.6.1.2.1.43.12.1.1.4', 'prtMarkerColorantValue', 'The name of the color of this The name of the color of this colorant using standardized string names from ISO 10175 (DPA) and ISO 10180 (SPDL)'],
    ['1.3.6.1.2.1.43.12.1.1.5', 'prtMarkerColorantTonality', 'The distinct levels of tonality realizable by a marking sub-unit when using this colorant'],
    ['1.3.6.1.2.1.43.13.4.1.1', 'prtMediaPathIndex', 'A unique value used by the printer to identify this media path'],
    ['1.3.6.1.2.1.43.13.4.1.2', 'prtMediaPathMaxSpeedPrintUnit', 'The unit of measure used in specifying the speed of all media paths in the printer'],
    ['1.3.6.1.2.1.43.13.4.1.3', 'prtMediaPathMediaSizeUnit', 'The units of measure of media size for use in calculating and relaying dimensional values for all media paths in the printer'],
    ['1.3.6.1.2.1.43.13.4.1.4', 'prtMediaPathMaxSpeed', 'The maximum printing speed of this media path expressed in prtMediaPathMaxSpeedUnits'],
    ['1.3.6.1.2.1.43.13.4.1.5', 'prtMediaPathMaxMediaFeedDir', 'The maximum physical media size in the feed direction of this media path expressed in units of measure specified by MediaSizeUnit'],
    ['1.3.6.1.2.1.43.13.4.1.6', 'prtMediaPathMaxMediaXFeedDir', 'The maximum physical media size across the feed direction of this media path expressed in units of measure specified by MediaSizeUnit'],
    ['1.3.6.1.2.1.43.13.4.1.7', 'prtMediaPathMinMediaFeedDir', 'The minimum physical media size in the feed direction of this media path expressed in units of measure specified by MediaSizeUnit'],
    ['1.3.6.1.2.1.43.13.4.1.8', 'prtMediaPathMinMediaXFeedDir', 'The minimum physical media size across the feed direction of this media path expressed in units of measure specified by MediaSizeUnit'],
    ['1.3.6.1.2.1.43.13.4.1.9', 'prtMediaPathType', 'The type of the media path for this media path'],
    ['1.3.6.1.2.1.43.13.4.1.10', 'prtMediaPathDescription', 'The manufacturer-provided description of this media path in the localization specified by prtGeneralCurrentLocalization'],
    ['1.3.6.1.2.1.43.13.4.1.11', 'prtMediaPathStatus', 'The current status of this media path'],
    ['1.3.6.1.2.1.43.14.1.1.1', 'prtChannelIndex', 'A unique value used by the printer to identify this data channel'],
    ['1.3.6.1.2.1.43.14.1.1.2', 'prtChannelType', 'The type of this print data channel'],
    ['1.3.6.1.2.1.43.14.1.1.3', 'prtChannelProtocolVersion', 'The version of the protocol used on this channel'],
    ['1.3.6.1.2.1.43.14.1.1.4', 'prtChannelCurrentJobCntlLangIndex', 'The value of prtInterpreterIndex corresponding to the Control Language Interpreter for this channel'],
    ['1.3.6.1.2.1.43.14.1.1.5', 'prtChannelDefaultPageDescLangIndex', 'The value of prtInterpreterIndex corresponding to the Page Description Language Interpreter for this channel'],
    ['1.3.6.1.2.1.43.14.1.1.6', 'prtChannelState', 'The state of this print data channel'],
    ['1.3.6.1.2.1.43.14.1.1.7', 'prtChannelIfIndex', 'The value of ifIndex (in the ifTable; see the interface section of MIB-2/RFC 1213) which corresponds to this channel'],
    ['1.3.6.1.2.1.43.14.1.1.8', 'prtChannelStatus', 'The current status of the channel'],
    ['1.3.6.1.2.1.43.14.1.1.9', 'prtChannelInformation', 'Auxiliary information to allow a printing application to use the channel for data submission to the printer'],
    ['1.3.6.1.2.1.43.15.1.1.1', 'prtInterpreterIndex', 'A unique value for each PDL or control language for which there exists an interpreter or emulator in the printer'],
    ['1.3.6.1.2.1.43.15.1.1.2', 'prtInterpreterLangFamily', 'The family name of a Page Description Language (PDL) or control language which this interpreter in the printer can interpret or emulate'],
    ['1.3.6.1.2.1.43.15.1.1.3', 'prtInterpreterLangLevel', 'The level of the language which this interpreter is interpreting or emulating'],
    ['1.3.6.1.2.1.43.15.1.1.4', 'prtInterpreterLangVersion', 'The date code or version of the language which this interpreter is interpreting or emulating'],
    ['1.3.6.1.2.1.43.15.1.1.5', 'prtInterpreterDescription', 'A string to identify this interpreter in the localization specified by prtGeneralCurrentLocalization as opposed to the language which is being interpreted'],
    ['1.3.6.1.2.1.43.15.1.1.6', 'prtInterpreterVersion', 'The date code, version number, or other product specific information tied to this interpreter'],
    ['1.3.6.1.2.1.43.15.1.1.7', 'prtInterpreterDefaultOrientation', 'The current orientation default for this interpreter'],
    ['1.3.6.1.2.1.43.15.1.1.8', 'prtInterpreterFeedAddressability', 'The maximum interpreter addressability in the feed direction in 10000 prtMarkerAddressabilityUnit s (see prtMarkerAddressabilityFeedDir ) for this interpreter'],
    ['1.3.6.1.2.1.43.15.1.1.9', 'prtInterpreterXFeedAddressability', 'The maximum interpreter addressability in the cross feed direction in 10000 prtMarkerAddressabilityUnit s (see prtMarkerAddressabilityXFeedDir) for this interpreter'],
    ['1.3.6.1.2.1.43.15.1.1.10', 'prtInterpreterDefaultCharSetIn', 'The default coded character set for input octets encountered outside a context in which the Page Description Language established the interpretation of the octets'],
    ['1.3.6.1.2.1.43.15.1.1.11', 'prtInterpreterDefaultCharSetOut', 'The default character set for data coming from this interpreter through the printers output channel'],
    ['1.3.6.1.2.1.43.15.1.1.12', 'prtInterpreterTwoWay', 'Indicates whether or not this interpreter returns information back to the host'],
    ['1.3.6.1.2.1.43.16.5.1.1', 'prtConsoleDisplayBufferIndex', 'A unique value for each console line in the printer'],
    ['1.3.6.1.2.1.43.16.5.1.2', 'prtConsoleDisplayBufferText', 'The content of a line in the logical display buffer of the operators console of the printer'],
    ['1.3.6.1.2.1.43.17.6.1.1', 'prtConsoleLightIndex', 'A unique value used by the printer to identify this light'],
    ['1.3.6.1.2.1.43.17.6.1.2', 'prtConsoleOnTime', 'The on time in milliseconds of blinking of this light'],
    ['1.3.6.1.2.1.43.17.6.1.3', 'prtConsoleOffTime', 'The off time in milliseconds of blinking of this light'],
    ['1.3.6.1.2.1.43.17.6.1.4', 'prtConsoleColor', 'The color of this light'],
    ['1.3.6.1.2.1.43.17.6.1.5', 'prtConsoleDescription', 'The vendor description or label of this light in the localization specified by prtConsoleLocalization'],
    ['1.3.6.1.2.1.43.18.1.1.1', 'prtAlertIndex', 'The index value used to determine which alerts have been added or removed from the alert table'],
    ['1.3.6.1.2.1.43.18.1.1.2', 'prtAlertSeverityLevel', 'The level of severity of this alert table entry'],
    ['1.3.6.1.2.1.43.18.1.1.3', 'prtAlertTrainingLevel', 'The level of training required to handle this alert'],
    ['1.3.6.1.2.1.43.18.1.1.4', 'prtAlertGroup', 'The type of sub-unit within the printer model that this alert is related'],
    ['1.3.6.1.2.1.43.18.1.1.5', 'prtAlertGroupIndex', 'An index of the row within the principle table in the group identified by prtAlertGroup that represents the sub-unit of the printer that caused this alert'],
    ['1.3.6.1.2.1.43.18.1.1.6', 'prtAlertLocation', 'The sub-unit location that is defined by the printer manufacturer to further refine the location of this alert within the designated sub-unit'],
    ['1.3.6.1.2.1.43.18.1.1.7', 'prtAlertCode', 'The code that describes the type of alert for this entry in the table'],
    ['1.3.6.1.2.1.43.18.1.1.8', 'prtAlertDescription', 'A description of this alert entry in the localization specified by prtGeneralCurrentLocalization'],
    ['1.3.6.1.2.1.43.18.1.1.9', 'prtAlertTime', 'The value of sysUpTime at the time that this alert was generated'],
    ['1.3.6.1.2.1.43.18.2.0.1', 'printerV2Alert', 'This trap is sent whenever a critical event is added to the prtAlertTable'],
    ['1.3.6.1.2.1.43.30.1.1.1', 'finDeviceIndex', 'A unique value used to identify a finisher process'],
    ['1.3.6.1.2.1.43.30.1.1.2', 'finDeviceType', 'Defines the type of finishing process associated with this table row entry'],
    ['1.3.6.1.2.1.43.30.1.1.3', 'finDevicePresentOnOff', 'Indicates if this finishing device subunit is available and whether the device subunit is enabled'],
    ['1.3.6.1.2.1.43.30.1.1.4', 'finDeviceCapacityUnit', 'The unit of measure for specifying the capacity of this finisher device subunit'],
    ['1.3.6.1.2.1.43.30.1.1.5', 'finDeviceMaxCapacity', 'The maximum capacity of this finisher device subunit in finDeviceCapacityUnits'],
    ['1.3.6.1.2.1.43.30.1.1.6', 'finDeviceCurrentCapacity', 'The current capacity of this finisher device subunit in finDeviceCapacityUnits'],
    ['1.3.6.1.2.1.43.30.1.1.7', 'finDeviceAssociatedMediaPaths', 'Indicates the media paths which can supply media for this finisher device'],
    ['1.3.6.1.2.1.43.30.1.1.8', 'finDeviceAssociatedOutputs', 'Indicates the printer output subunits this finisher device subunit services'],
    ['1.3.6.1.2.1.43.30.1.1.9', 'finDeviceStatus', 'Indicates the current status of this finisher device subunit'],
    ['1.3.6.1.2.1.43.30.1.1.10', 'finDeviceDescription', 'A free form text description of this device subunit in the localization specified by prtGeneralCurrentLocalization'],
    ['1.3.6.1.2.1.43.31.1.1.1', 'finSupplyIndex', 'A unique value used by a finisher to identify this supply container/receptacle'],
    ['1.3.6.1.2.1.43.31.1.1.2', 'finSupplyDeviceIndex', 'The value of finDeviceIndex corresponding to the finishing device subunit with which this finisher supply is associated'],
    ['1.3.6.1.2.1.43.31.1.1.3', 'finSupplyClass', 'This value indicates whether this supply entity represents a supply that is consumed or a container that is filled'],
    ['1.3.6.1.2.1.43.31.1.1.4', 'finSupplyType', 'The type of this supply'],
    ['1.3.6.1.2.1.43.31.1.1.5', 'finSupplyDescription', 'The description of this supply/receptacle in text useful for operators and management applications and in the localization specified by prtGeneralCurrentLocalization'],
    ['1.3.6.1.2.1.43.31.1.1.6', 'finSupplyUnit', 'Unit of measure of this finisher supply container or receptacle'],
    ['1.3.6.1.2.1.43.31.1.1.7', 'finSupplyMaxCapacity', 'The maximum capacity of this supply container/receptacle expressed in Supply Units'],
    ['1.3.6.1.2.1.43.31.1.1.8', 'finSupplyCurrentLevel', 'The current level if this supply is a container; the remaining space if this supply is a receptacle'],
    ['1.3.6.1.2.1.43.31.1.1.9', 'finSupplyColorName', 'The PWG Standardized Media Names specification [PWGMEDIA], section 4 Media Color Names, contains the recommended values for this object'],
    ['1.3.6.1.2.1.43.32.1.1.1', 'finSupplyMediaInputIndex', 'A unique value used by a finisher to identify this supply media input subunit'],
    ['1.3.6.1.2.1.43.32.1.1.2', 'finSupplyMediaInputDeviceIndex', 'The value of finDeviceIndex corresponding to the finishing device subunit with which this finisher media supply is associated'],
    ['1.3.6.1.2.1.43.32.1.1.3', 'finSupplyMediaInputSupplyIndex', 'The value of finDeviceIndex corresponding to the finishing device subunit with which this finisher media supply is associated'],
    ['1.3.6.1.2.1.43.32.1.1.4', 'finSupplyMediaInputType', 'The type of technology (discriminated primarily according to the feeder mechanism type) employed by the input subunit'],
    ['1.3.6.1.2.1.43.32.1.1.5', 'finSupplyMediaInputDimUnit', 'The unit of measure for specifying dimensional values for this input device'],
    ['1.3.6.1.2.1.43.32.1.1.6', 'finSupplyMediaInputMediaDimFeedDir', 'This object provides the value of the dimension in the feed direction of the media that is placed or will be placed in this input device'],
    ['1.3.6.1.2.1.43.32.1.1.7', 'finSupplyMediaInputMediaDimXFeedDir', 'This object provides the value of the dimension across the feed direction of the media that is placed or will be placed in this input device'],
    ['1.3.6.1.2.1.43.32.1.1.8', 'finSupplyMediaInputStatus', 'This value indicates the current status of this input device'],
    ['1.3.6.1.2.1.43.32.1.1.9', 'finSupplyMediaInputMediaName', 'The name of the current media contained in this input device'],
    ['1.3.6.1.2.1.43.32.1.1.10', 'finSupplyMediaInputName', 'The name assigned to this input subunit'],
    ['1.3.6.1.2.1.43.32.1.1.11', 'finSupplyMediaInputDescription', 'A free form text description of this input subunit in the localization specified by prtGeneralCurrentLocalization'],
    ['1.3.6.1.2.1.43.32.1.1.12', 'finSupplyMediaInputSecurity', 'Indicates if this subunit has some security associated with it'],
    ['1.3.6.1.2.1.43.32.1.1.13', 'finSupplyMediaInputMediaWeight', 'The weight of the media associated with this Input device in grams per meter squared'],
    ['1.3.6.1.2.1.43.32.1.1.14', 'finSupplyMediaInputMediaThickness', 'This object identifies the thickness of the input media processed by this document input subunit measured in micrometers'],
    ['1.3.6.1.2.1.43.32.1.1.15', 'finSupplyMediaInputMediaType', 'The PWG Standardized Media Names specification [PWGMEDIA], section 3 Media Type Names, contains the recommended values for this object'],
    ['1.3.6.1.2.1.43.33.1.1.1', 'finDeviceAttributeTypeIndex', 'Defines the attribute type represented by this row'],
    ['1.3.6.1.2.1.43.33.1.1.2', 'finDeviceAttributeInstanceIndex', 'An index that allows the discrimination of an attribute instance when the same attribute occurs multiple times for a specific instance of a finisher function'],
    ['1.3.6.1.2.1.43.33.1.1.3', 'finDeviceAttributeValueAsInteger', 'Defines the integer value of the attribute'],
    ['1.3.6.1.2.1.43.33.1.1.4', 'finDeviceAttributeValueAsOctets', 'Contains the octet string value of the attribute']

]



console.log(createList('printers', printers));